name: "CI Tests"

on:
    pull_request:
    push:

jobs:
    php74:
        name: PHP 8
        runs-on: ubuntu-latest
        steps:
          - name: "Checkout"
            uses: "actions/checkout@v2"
            with:
              fetch-depth: 2

          - name: "Install PHP 7.4"
            uses: "shivammathur/setup-php@v2"
            with:
              php-version: "7.4"

          - name: "Cache composer packages"
            uses: "actions/cache@v2"
            with:
              path: "~/.composer/cache"
              key: "php-composer-locked-${{ hashFiles('composer.lock') }}"
              restore-keys: "php-composer-locked-"

          - name: "Install dependencies with composer"
            run: "composer install --no-interaction"

          - name: "Run PHPUnit Tests"
            run: "composer test"

          - name: "Run PHP CS Check"
            run: "composer cs-check"

          - name: "Run PHPStan"
            run: "composer analyze"

          - name: "Run Psalm"
            run: "composer psalm"

    php8:
        name: PHP 8
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: "actions/checkout@v2"
              with:
                  fetch-depth: 2

            - name: "Install PHP 8"
              uses: "shivammathur/setup-php@v2"
              with:
                  php-version: "8"

            - name: "Cache composer packages"
              uses: "actions/cache@v2"
              with:
                  path: "~/.composer/cache"
                  key: "php-composer-locked-${{ hashFiles('composer.lock') }}"
                  restore-keys: "php-composer-locked-"

            - name: "Install dependencies with composer"
              run: "composer install --no-interaction"

            - name: "Run PHPUnit Tests"
              run: "composer test"

            - name: "Run PHP CS Check"
              run: "composer cs-check"

            - name: "Run PHPStan"
              run: "composer analyze"

            - name: "Run Psalm"
              run: "composer psalm"
