name: "CI Tests"

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  phpunit:
    name: "PHP ${{ matrix.php }} - PHPUnit"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1', '8.2', '8.3', '8.4' ]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: "Cache composer packages"
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: php-composer-locked-${{ hashFiles('composer.lock') }}
          restore-keys: php-composer-locked-

      - name: "Install dependencies"
        run: composer install --no-interaction

      - name: "Run PHPUnit Tests"
        run: composer test

  cs:
    name: "PHP ${{ matrix.php }} - CS Check"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1', '8.2', '8.3', '8.4' ]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: "Cache composer packages"
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: php-composer-locked-${{ hashFiles('composer.lock') }}
          restore-keys: php-composer-locked-

      - name: "Install dependencies"
        run: composer install --no-interaction

      - name: "Run PHP CS Check"
        run: composer cs-check

  phpmd:
    name: "PHP ${{ matrix.php }} - PHP Mess Detector"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1', '8.2', '8.3', '8.4' ]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: "Cache composer packages"
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: php-composer-locked-${{ hashFiles('composer.lock') }}
          restore-keys: php-composer-locked-

      - name: "Install dependencies"
        run: composer install --no-interaction

      - name: "Run PHP Mess Detector"
        run: composer phpmd

  psalm:
    name: "PHP ${{ matrix.php }} - Psalm"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1', '8.2', '8.3', '8.4' ]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: "Cache composer packages"
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: php-composer-locked-${{ hashFiles('composer.lock') }}
          restore-keys: php-composer-locked-

      - name: "Install dependencies"
        run: composer install --no-interaction

      - name: "Run Psalm"
        run: composer psalm

  infection:
    name: "PHP ${{ matrix.php }} - Infection"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1', '8.2', '8.3', '8.4' ]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: "Cache composer packages"
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: php-composer-locked-${{ hashFiles('composer.lock') }}
          restore-keys: php-composer-locked-

      - name: "Install dependencies"
        run: composer install --no-interaction

      - name: "Run infection (with badge upload)"
        if: matrix.php == '8.3'
        env:
          INFECTION_BADGE_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
        run: composer infection-ci

      - name: "Run infection"
        if: matrix.php != '8.3'
        run: composer infection-ci
